### ISSUE TITLE
IMAP fetch causes UTF-8 Format Exception

### ISSUE THREAD

**Issue by Tienisto** [Enough-Software/enough_mail#102]
Hello there,

recently I tried calling `await imapClient.uidFetchMessages(fetchSequence, '(ENVELOPE BODY[1])')` which causes an error.
`await imapClient.uidFetchMessages(fetchSequence, '(ENVELOPE)')` however works.

After some debugging I think it is because of the `windows-1252` encoding.
Here is the header of the mail causing this issue:
```
Content-Type: text/html; charset=windows-1252
Content-Transfer-Encoding: 8bit
```

Stacktrace:
```
E/flutter (25810): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: FormatException: Invalid UTF-8 byte (at offset 11)
E/flutter (25810): #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1783:7)
E/flutter (25810): #1      Utf8Decoder.convert (dart:convert/utf.dart:321:42)
E/flutter (25810): #2      new ImapResponseLine.raw (package:enough_mail/src/imap/imap_response_line.dart:15:21)
E/flutter (25810): #3      ImapResponseReader._checkResponse (package:enough_mail/src/imap/imap_response_reader.dart:50:40)
E/flutter (25810): #4      ImapResponseReader.onData (package:enough_mail/src/imap/imap_response_reader.dart:34:11)
E/flutter (25810): #5      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (25810): #6      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (25810): #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (25810): #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (25810): #9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
E/flutter (25810): #10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
E/flutter (25810): #11     _StreamController._add (dart:async/stream_controller.dart:682:7)
E/flutter (25810): #12     _StreamController.add (dart:async/stream_controller.dart:624:5)
E/flutter (25810): #13     _Socket._onData (dart:io-patch/socket_patch.dart:2044:41)
E/flutter (25810): #14     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (25810): #15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (25810): #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (25810): #17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (25810): #18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
E/flutter (25810): #19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:808:19)
E/flutter (25810): #20     _StreamController._add (dart:async/stream_controller.dart:682:7)
E/flutter (25810): #21     _StreamController.add (dart:async/stream_controller.dart:624:5)
E/flutter (25810): #22     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1002:19)
E/flutter (25810): #23     _rootRun (dart:async/zone.dart:1182:47)
E/flutter (25810): #24     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (25810): #25     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (25810): #26     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (25810): #27     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (25810): #28     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (25810): #29     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
E/flutter (25810): #30     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (25810): #31     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter (25810): #32     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter (25810): #33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

```

**Comment by robert-virkus** [comment]
Thanks for the report and the fallback solution! I guess we need proper encoding support within dart...

**Comment by robert-virkus** [comment]
I have now released v0.0.35 with your intermediate fix. I guess that the API should not try to decode raw byte arrays unless absolutely needed. I will ponder about that a bit more.

**Comment by Tienisto** [comment]
Thanks!

**Comment by robert-virkus** [comment]
Version 0.1.0 does not try to decode binary data before it is needed, so this should be solved,
