### ISSUE TITLE
IMAP client

### ISSUE THREAD

**Issue by Abhishek01039** [Enough-Software/enough_mail#104]
How to get the email for a specific email address using `IMAP`?
@robert-virkus can you please let me know 
Thanks

**Comment by robert-virkus** [comment]
You will be looking for `ImapClient.searchMessages(String criteria)`. For possible criteria compare https://tools.ietf.org/html/rfc3501#section-6.4.4 

In your case:
```dart
final response = await imapClient.searchMessages('FROM user@domain.com'); 
```

Please close if that's what you needed.

**Comment by Abhishek01039** [comment]
if we use 
```final response = await imapClient.searchMessages('FROM user@domain.com'); ```
Then how to handle this ?
```
if (fetchResponse.isOkStatus) {
        var messages = fetchResponse.result.messages;
        for (var message in messages) {
          printMessage(message);
        }
      }
```

**Comment by robert-virkus** [comment]
With `ImapClient` you are using the low level API, which requires more work on your behalf.

Here are the relevant API docs:
* `searchMessages`: https://pub.dev/documentation/enough_mail/latest/imap_imap_client/ImapClient/searchMessages.html
* `SearchImapResult`: https://pub.dev/documentation/enough_mail/latest/imap_response/SearchImapResult-class.html

```dart
final searchResponse = await imapClient.searchMessages('FROM user@domain.com');
if (searchResponse.isOkStatus) {
  print('found the following matching sequence IDs: ${searchResponse.result.ids}');
}
```

Hope this helps!

**Comment by Abhishek01039** [comment]
Then how to get the body of emails and the date of emails also?
@robert-virkus

**Comment by Abhishek01039** [comment]
Got the solution @robert-virkus 
```
if (inboxResponse.isOkStatus) {
      // fetch 10 most recent messages:
      final fetchResponse = await client.fetchRecentMessages(
          messageCount: 10, criteria: 'BODY.PEEK[]');

      if (fetchResponse.isOkStatus) {
        final messages = fetchResponse.result.messages;
        for (var message in messages) {
          for (var j in message.from) {
            if (j.email == 'notifications@github.com') {
              printMessage(message);
              break;
            }
          }
        }
      }
    }
```

**Comment by Abhishek01039** [comment]
Now I am getting the error while login to email 
```
Launching email_enough.dart on ASUS X00TD in debug mode...
email_enough.dart:1
Parameter format not correct -
√ Built build\app\outputs\flutter-apk\app-debug.apk.
D/AdobeExperienceSDK(12018): RemoteDownloader - File not found. (https://assets.adobedtm.com/###.json)
W/AdobeExperienceSDK(12018): AndroidHttpConnection - Could not get the input stream. (java.io.FileNotFoundException: https://assets.adobedtm.com/###.json)
D/AdobeExperienceSDK(12018): ConfigurationExtension - Problem while downloading config.
D/AdobeExperienceSDK(12018): CacheManager - Cached Files - File has not previously been cached (https://assets.adobedtm.com/###.json).
D/AdobeExperienceSDK(12018): ConfigurationExtension - Either there was no cached config, or there was a problem loading the cached config.
W/AdobeExperienceSDK(12018): ConfigurationExtension - Unable to fetch config. Rolling back to previous configuration.
D/AdobeExperienceSDK(12018): CacheManager - Cached Files - File has not previously been cached (https://assets.adobedtm.com/###.json).
D/AdobeExperienceSDK(12018): HttpConnectionHandler - Connecting to URL https://assets.adobedtm.com/###.json (GET)
D/AdobeExperienceSDK(12018): RemoteDownloader - File not found. (https://assets.adobedtm.com/###.json)
W/AdobeExperienceSDK(12018): AndroidHttpConnection - Could not get the input stream. (java.io.FileNotFoundException: https://assets.adobedtm.com/###.json)
D/AdobeExperienceSDK(12018): ConfigurationExtension - Problem while downloading config.
D/AdobeExperienceSDK(12018): CacheManager - Cached Files - File has not previously been cached (https://assets.adobedtm.com/###.json).
D/AdobeExperienceSDK(12018): ConfigurationExtension - Either there was no cached config, or there was a problem loading the cached config.
W/AdobeExperienceSDK(12018): ConfigurationExtension - Unable to fetch config. Rolling back to previous configuration.
I/FA      (12018): Tag Manager is not found and thus will not be used
W/ConnectionTracker(12018): Exception thrown while unbinding
W/ConnectionTracker(12018): java.lang.IllegalArgumentException: Service not registered: lu@60fc735
W/ConnectionTracker(12018): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1562)
W/ConnectionTracker(12018): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1692)
W/ConnectionTracker(12018): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:717)
W/ConnectionTracker(12018): 	at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204516067@20.45.16 (100408-0):1)
W/ConnectionTracker(12018): 	at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204516067@20.45.16 (100408-0):2)
W/ConnectionTracker(12018): 	at lv.E(:com.google.android.gms.dynamite_measurementdynamite@204516067@20.45.16 (100408-0):9)
W/ConnectionTracker(12018): 	at lf.a(:com.google.android.gms.dynamite_measurementdynamite@204516067@20.45.16 (100408-0):3)
W/ConnectionTracker(12018): 	at ef.run(:com.google.android.gms.dynamite_measurementdynamite@204516067@20.45.16 (100408-0):3)
W/ConnectionTracker(12018): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
W/ConnectionTracker(12018): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/ConnectionTracker(12018): 	at iy.run(:com.google.android.gms.dynamite_measurementdynamite@204516067@20.45.16 (100408-0):5)
Connecting to VM Service at ws://127.0.0.1:61913/10eDINcP2ys=/ws
I/flutter (12018): Connecting to imap.gmail.com:993  using a secure socket...
I/flutter (12018): Socket connected.
I/flutter (12018): C: a0 LOGIN automation.mylawn@gmail.com (password scrambled)
I/flutter (12018): S: * OK Gimap ready for requests from 1.38.165.111 u15mb609532972pjn

```
what could be the problem?

**Comment by Abhishek01039** [comment]
Thanks, @robert-virkus

**Comment by robert-virkus** [comment]
Glad you found a solution that works for you. The `imapClient.searchMessages()` call should return a `MessageSequence`, that would make things easier. Will keep that in mind for the future API versions.

**Comment by Abhishek01039** [comment]
ok, sure!
Thanks, @robert-virkus
