### ISSUE TITLE
imap login error 

### ISSUE THREAD

**Issue by inits** [Enough-Software/enough_mail#159]
name: dtest
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  enough_mail: ^1.3.1

dev_dependencies:
  pedantic: ^1.10.0

###################################

inits@QiaosMobile:~/Desktop/test/dtest$ dart run bin/dtest.dart 
discovering settings for  915068877@qq.com...
connecting to qq.com.
A: connecting to server imap.qq.com:993 - secure: true
S: * OK [CAPABILITY IMAP4 IMAP4rev1 ID AUTH=PLAIN AUTH=LOGIN AUTH=XOAUTH2 NAMESPACE] QQMail XMIMAP4Server ready

C: a0 LOGIN "915068877@qq.com" "(password scrambled)"
S: a0 OK Success login ok

Unhandled exception:
type 'Null' is not a subtype of type 'FutureOr<List<Capability>>'
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:46:41)
#1      ImapClient.onCommandResult (package:enough_mail/imap/imap_client.dart:1653:26)
#2      ImapClient.onServerResponse (package:enough_mail/imap/imap_client.dart:1636:7)
#3      ImapResponseReader.onData (package:enough_mail/src/imap/imap_response_reader.dart:37:25)
#4      ImapClient.onDataReceived (package:enough_mail/imap/imap_client.dart:213:25)
#5      ClientBase._onDataReceived (package:enough_mail/src/util/client_base.dart:122:7)
#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1546:10)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#9      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#10     _StreamController._add (dart:async/stream_controller.dart:607:7)
#11     _StreamController.add (dart:async/stream_controller.dart:554:5)
#12     _Socket._onData (dart:io-patch/socket_patch.dart:2160:41)
#13     _RootZone.runUnaryGuarded (dart:async/zone.dart:1546:10)
#14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#16     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#17     _StreamController._add (dart:async/stream_controller.dart:607:7)
#18     _StreamController.add (dart:async/stream_controller.dart:554:5)
#19     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:991:19)
#20     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#21     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:395:19)
#22     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:426:5)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
inits@QiaosMobile:~/Desktop/test/dtest$

**Comment by robert-virkus** [comment]
Thanks for the bug report. I tried signing up for QQ mail at https://ssl.zc.qq.com/v3/index-en.html but I lack the necessary Chinese, HK, Macao or Taiwanese phone number. If you happen to have a suitable test account or could help me signin up, please get in touch with via robert-at-enough-dot-de. Thank you!

**Comment by inits** [comment]
i debug this , find that is chinese qq mail imap server problem,that return capabilities is null ,

**Comment by robert-virkus** [comment]
Thanks, can you post the log of client requests and server responses, then I can add a test case for this behavior.

**Comment by inits** [comment]
qq chinese mail:

inits@QiaosMobile:~/Desktop/test/dtest$ dart run bin/dtest.dart |more
A: connecting to server imap.qq.com:993 - secure: true
S: * OK [CAPABILITY IMAP4 IMAP4rev1 ID AUTH=PLAIN AUTH=LOGIN AUTH=XOAUTH2 NAMESPACE] QQMail XMIMAP4Server ready

C: a0 LOGIN "915068877@qq.com" "(password scrambled)"
S: a0 OK Success login ok

line:a0 OK Success login ok
[a0 OK Success login ok]
isok: true
isokdetal: a0 OK Success login ok
isokdparsetxt: OK Success login ok
isok caps: ogin ok
isok1: [ogin, ok]
qiaosd--debug##########
[ogin, ok]


gmail :

inits@QiaosMobile:~/Desktop/test/dtest$ dart run bin/dtest.dart |more
A: connecting to server imap.gmail.com:993 - secure: true
S: * OK Gimap ready for requests from 13.113.83.140 p103mb65724869ivj

C: a0 LOGIN "pqm1989@gmail.com" "(password scrambled)"
S: * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 UIDPLUS COMPRESS=DEFLATE ENABLE MOVE CONDSTORE ESEARCH UTF8=ACCEPT LIST-EXTENDED LIST-STATUS LITERAL- SPECIAL-USE APPENDLIMIT=35651584

C: subline: * CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 UIDPLUS COMPRESS=DEFLATE ENABLE MOVE CONDSTORE ESEARCH UTF8=ACCEPT LIST-EXTENDED LIST-STATUS LITERAL- SPECIAL-USE APPENDLIMIT=35651584
isok caps: IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 UIDPLUS COMPRESS=DEFLATE ENABLE MOVE CONDSTORE ESEARCH UTF8=ACCEPT LIST-EXTENDED LIST-STATUS LITERAL- SPECIAL-USE APPENDLIMIT=35651584
S: a0 OK pqm1989@gmail.com authenticated (Success)

C: subline: a0 OK pqm1989@gmail.com authenticated (Success)
line:a0 OK pqm1989@gmail.com authenticated (Success)
[a0 OK pqm1989@gmail.com authenticated (Success)]
isok: true
isokdetal: a0 OK pqm1989@gmail.com authenticated (Success)
false
isok1: [IMAP4rev1, UNSELECT, IDLE, NAMESPACE, QUOTA, ID, XLIST, CHILDREN, X-GM-EXT-1, UIDPLUS, COMPRESS=DEFLATE, ENABLE, MOVE, CONDSTORE, ESEARCH, UTF8=ACCEPT, LIST-EXTENDED, LIST-STATUS, LITERAL-, SPECIAL-USE, APPENDLIMIT=35651584]
qiaosd--debug##########
[IMAP4rev1, UNSELECT, IDLE, NAMESPACE, QUOTA, ID, XLIST, CHILDREN, X-GM-EXT-1, UIDPLUS, COMPRESS=DEFLATE, ENABLE, MOVE, CONDSTORE, ESEARCH, UTF8=ACCEPT, LIST-EXTENDED, LIST-STATUS, LITERAL-, SPECIAL-USE, APPENDLIMIT=35651584]

dif is "C: subline:" , chinese qq mail didn't have "* CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA ID XLIST CHILDREN X-GM-EXT-1 UIDPLUS COMPRESS=DEFLATE ENABLE MOVE CONDSTORE ESEARCH UTF8=ACCEPT LIST-EXTENDED LIST-STATUS LITERAL- SPECIAL-USE APPENDLIMIT=35651584"

**Comment by robert-virkus** [comment]
Thanks, I could fix this problem and have created the new release v1.3.2 with the fix
