### ISSUE TITLE
IMAP/MIME: Null exception on fetchMessagesByCriteria()

### ISSUE THREAD

**Issue by ali7234** [Enough-Software/enough_mail#37]
Null Exception occurred when trying to fetch email with sequence Id. 
**Code**
```
var fetchResponse = await S.sImapClient.fetchMessagesByCriteria('$sequenceID (BODY BODY.PEEK[])');
```
**Log**
```
E/flutter (23042): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Invalid argument(s): The source must not be null
E/flutter (23042): #0      int.tryParse (dart:core-patch/integers_patch.dart:107:25)
E/flutter (23042): #1      FetchParser._parseBody (package:enough_mail/src/imap/fetch_parser.dart:240:24)
E/flutter (23042): #2      FetchParser._parseFetch (package:enough_mail/src/imap/fetch_parser.dart:74:11)
E/flutter (23042): #3      FetchParser.parseUntagged (package:enough_mail/src/imap/fetch_parser.dart:32:11)
E/flutter (23042): #4      CommandTask.parseUntaggedResponse (package:enough_mail/src/imap/command.dart:73:21)
E/flutter (23042): #5      ImapClient.onUntaggedResponse (package:enough_mail/imap/imap_client.dart:966:31)
E/flutter (23042): #6      ImapClient.onServerResponse (package:enough_mail/imap/imap_client.dart:934:7)
E/flutter (23042): #7      ImapResponseReader._checkResponse (package:enough_mail/src/imap/imap_response_reader.dart:72:28)
E/flutter (23042): #8      ImapResponseReader._checkResponse (package:enough_mail/src/imap/imap_response_reader.dart:53:9)
E/flutter (23042): #9      ImapResponseReader.onData (package:enough_mail/src/imap/imap_response_reader.dart:22:7)
E/flutter (23042): #10     _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter (23042): #11     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (23042): #12     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter (23042): #13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (23042): #14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
E/flutter (23042): #15     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
E/flutter (23042): #16     _StreamController._add (dart:async/stream_controller.dart:655:7)
E/flutter (23042): #17     _StreamController.add (dart:async/stream_controller.dart:597:5)
E/flutter (23042): #18     _Socket._onData (dart:io-patch/socket_patch.dart:1982:41)
E/flutter (23042): #19     _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter (23042): #20     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (23042): #21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter (23042): #22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (23042): #23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
E/flutter (23042): #24     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
E/flutter (23042): #25     _StreamController._add (dart:async/stream_controller.dart:655:7)
E/flutter (23042): #26     _StreamController.add (dart:async/stream_controller.dart:597:5)
E/flutter (23042): #27     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1018:19)
E/flutter (23042): #28     _rootRun (dart:async/zone.dart:1180:38)
E/flutter (23042): #29     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (23042): #30     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (23042): #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter (23042): #32     _rootRun (dart:async/zone.dart:1184:13)
E/flutter (23042): #33     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (23042): #34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
E/flutter (23042): #35     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter (23042): #36     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (23042): #37     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (23042): #38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (23042):
```
**Note**
This error occurred on the specific email not all the emails. Also, please guide about the messageId,
and messageId is null for each MimeMessage.

**Comment by robert-virkus** [comment]
Hi Ali, many thanks for the report, it seems that parsing that message - or perhaps of the previous message - fails ungracefully.
Would it be possible to get the IMAP response (by enabling logging on the imap client: `var client = ImapClient(isLogEnabled: true);`). Please remove any personal information from the log or send it as a direct message. 
You can also check if upgrading to v0.0.17 helps you.

In regards to `messageId`, this is currently only populated when fetching the envelope data. Please note that I plan to refactor this part as the project is now approaching complete IMAP4 rev1 support.

**Comment by ali7234** [comment]
**LOG BODYSTRUCTURE**
```
I/flutter ( 7699): S: * 27 FETCH (BODYSTRUCTURE (((("text" "plain" ("charset" "us-ascii") NIL NIL "7bit" 7641 499 NIL NIL NIL NIL)("text" "html" ("charset" "us-ascii") NIL NIL "quoted-printable" 75745 1357 NIL NIL NIL NIL) "alternative" ("boundary" "----=_NextPart_002_0DA3_01D59FD9.4AA40340") NIL NIL NIL)("image" "png" ("name" "image002.png") "<image002.png@server>" NIL "base64" 28930
NIL NIL NIL NIL)("image" "png" ("name" "image004.png") "<image004.png@server>" NIL "base64" 3286 NIL NIL NIL NIL)("image"
"png" ("name" "image006.png") "<image006.png@server>" NIL "base64" 3552 NIL NIL NIL NIL)("image" "png" ("name" "image016.png") "<image016.png@server>" NIL "base64" 29424 NIL NIL NIL NIL)("image" "png" ("name" "image017.png") "<image017.png@server>" NIL "base64" 3290 NIL NIL NIL NIL)("image" "png" ("name" "image018.png") "<image018.png@server>" NIL "base64" 3552 NIL NIL NIL NIL) "related" ("boundary" "----=_NextPart_001_0DA2_01D59FD9.4AA40340") NIL NIL NIL)("appl
E/flutter ( 7699): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Invalid argument(s): The source must not be null
E/flutter ( 7699): #0      int.tryParse (dart:core-patch/integers_patch.dart:107:25)
E/flutter ( 7699): #1      FetchParser._parseBody (package:enough_mail/src/imap/fetch_parser.dart:302:24)
E/flutter ( 7699): #2      FetchParser._parseBodyStructure (package:enough_mail/src/imap/fetch_parser.dart:361:5)
E/flutter ( 7699): #3      FetchParser._parseFetch (package:enough_mail/src/imap/fetch_parser.dart:77:11)
E/flutter ( 7699): #4      FetchParser.parseUntagged (package:enough_mail/src/imap/fetch_parser.dart:32:11)
E/flutter ( 7699): #5      CommandTask.parseUntaggedResponse (package:enough_mail/src/imap/command.dart:73:21)
E/flutter ( 7699): #6      ImapClient.onUntaggedResponse (package:enough_mail/imap/imap_client.dart:965:31)
E/flutter ( 7699): #7      ImapClient.onServerResponse (package:enough_mail/imap/imap_client.dart:933:7)
E/flutter ( 7699): #8      ImapResponseReader._checkResponse (package:enough_mail/src/imap/imap_response_reader.dart:72:28)
E/flutter ( 7699): #9      ImapResponseReader._checkResponse (package:enough_mail/src/imap/imap_response_reader.dart:53:9)
E/flutter ( 7699): #10     ImapResponseReader.onData (package:enough_mail/src/imap/imap_response_reader.dart:22:7)
E/flutter ( 7699): #11     _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter ( 7699): #12     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 7699): #13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter ( 7699): #14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter ( 7699): #15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
E/flutter ( 7699): #16     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
E/flutter ( 7699): #17     _StreamController._add (dart:async/stream_controller.dart:655:7)
E/flutter ( 7699): #18     _StreamController.add (dart:async/stream_controller.dart:597:5)
E/flutter ( 7699): #19     _Socket._onData (dart:io-patch/socket_patch.dart:1982:41)
E/flutter ( 7699): #20     _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter ( 7699): #21     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 7699): #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter ( 7699): #23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter ( 7699): #24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
E/flutter ( 7699): #25     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
E/flutter ( 7699): #26     _StreamController._add (dart:async/stream_controller.dart:655:7)
E/flutter ( 7699): #27     _StreamController.add (dart:async/stream_controller.dart:597:5)
E/flutter ( 7699): #28     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1018:19)
E/flutter ( 7699): #29     _rootRun (dart:async/zone.dart:1180:38)
E/flutter ( 7699): #30     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 7699): #31     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter ( 7699): #32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter ( 7699): #33     _rootRun (dart:async/zone.dart:1184:13)
E/flutter ( 7699): #34     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 7699): #35     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
E/flutter ( 7699): #36     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter ( 7699): #37     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter ( 7699): #38     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter ( 7699): #39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter ( 7699):
```
**Log BODY**
```
I/flutter ( 7699): C: a25 FETCH 32 (BODY BODY.PEEK[])
I/flutter ( 7699): S: * 32 FETCH (BODY (((("text" "plain" ("charset" "us-ascii") NIL NIL "7bit" 10252 819)("text" "html" ("charset" "us-ascii") NIL NIL "quoted-printable" 154063 2645) "alternative")("image" "png" ("name" "image001.png") "<image001.png@server>" NIL "base64" 29038)("image" "png" ("name" "image003.png") "<image003.png@server>" NIL "base64" 3286)("image" "png" ("name" "image005.png") "<image005.png@server>" NIL "base64" 3552)("image" "png" ("name" "image007.png") "<image007.png@server>" NIL "base64" 29874)("image" "png" ("name" "image008.png") "<image008.png@server>" NIL "base64" 3314)("image" "png" ("name" "image009.png") "<image009.png@server>" NIL "base64" 3576) "related")("application" "pdf" ("name" "name.pdf") NIL NIL "base64" 749602)("application" "pdf" ("name" "name.pdf") NIL NIL "base64" 611336)("application" "pdf" ("name" "name.pdf") NIL NIL "base64" 586426) "mixed") BODY[] {218
E/flutter ( 7699): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Invalid argument(s): The source must not be null
E/flutter ( 7699): #0      int.tryParse (dart:core-patch/integers_patch.dart:107:25)
E/flutter ( 7699): #1      FetchParser._parseBody (package:enough_mail/src/imap/fetch_parser.dart:302:24)
E/flutter ( 7699): #2      FetchParser._parseFetch (package:enough_mail/src/imap/fetch_parser.dart:74:11)
E/flutter ( 7699): #3      FetchParser.parseUntagged (package:enough_mail/src/imap/fetch_parser.dart:32:11)
E/flutter ( 7699): #4      CommandTask.parseUntaggedResponse (package:enough_mail/src/imap/command.dart:73:21)
E/flutter ( 7699): #5      ImapClient.onUntaggedResponse (package:enough_mail/imap/imap_client.dart:965:31)
E/flutter ( 7699): #6      ImapClient.onServerResponse (package:enough_mail/imap/imap_client.dart:933:7)
E/flutter ( 7699): #7      ImapResponseReader._checkResponse (package:enough_mail/src/imap/imap_response_reader.dart:72:28)
E/flutter ( 7699): #8      ImapResponseReader._checkResponse (package:enough_mail/src/imap/imap_response_reader.dart:53:9)
E/flutter ( 7699): #9      ImapResponseReader.onData (package:enough_mail/src/imap/imap_response_reader.dart:22:7)
E/flutter ( 7699): #10     _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter ( 7699): #11     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 7699): #12     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter ( 7699): #13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter ( 7699): #14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
E/flutter ( 7699): #15     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
E/flutter ( 7699): #16     _StreamController._add (dart:async/stream_controller.dart:655:7)
E/flutter ( 7699): #17     _StreamController.add (dart:async/stream_controller.dart:597:5)
E/flutter ( 7699): #18     _Socket._onData (dart:io-patch/socket_patch.dart:1982:41)
E/flutter ( 7699): #19     _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter ( 7699): #20     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter ( 7699): #21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter ( 7699): #22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter ( 7699): #23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
E/flutter ( 7699): #24     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
E/flutter ( 7699): #25     _StreamController._add (dart:async/stream_controller.dart:655:7)
E/flutter ( 7699): #26     _StreamController.add (dart:async/stream_controller.dart:597:5)
E/flutter ( 7699): #27     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1018:19)
E/flutter ( 7699): #28     _rootRun (dart:async/zone.dart:1180:38)
E/flutter ( 7699): #29     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 7699): #30     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter ( 7699): #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter ( 7699): #32     _rootRun (dart:async/zone.dart:1184:13)
E/flutter ( 7699): #33     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 7699): #34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
E/flutter ( 7699): #35     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter ( 7699): #36     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter ( 7699): #37     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter ( 7699): #38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter ( 7699):
```
**Note**
Using the latest version 0.0.17

**Comment by robert-virkus** [comment]
Thanks, I can reproduce at least the BODY problem, for some reason the BODYSTRUCTURE response is not complete. It seems that the previous BODY parsing does work well using nested structures. Will update once the problem is fixed, but I guess some API changes are required along the way.

**Comment by robert-virkus** [comment]
Please upgrade to v0.0.18, this should fix the problems. Please note the API changes when accessing the MimeMessage.body element, this is now close to the normal MimeMessage API. Compare https://pub.dev/documentation/enough_mail/latest/mime_message/BodyPart-class.html for details.

When the problems are fixed for you, please close this bug.

**Comment by ali7234** [comment]
Issue Resolved, Thanks
